import type { AvailabilitySlot } from "@/features/doctor-portal/availability/types";

import { DEMO_DOCTOR, DEMO_DOCTOR_2 } from "@/lib/mock-data/accounts";

export const availabilitySlots: AvailabilitySlot[] = [
  // Dr. Anika Rao — this week
  {
    id: "slot-001",
    doctorId: DEMO_DOCTOR.id,
    date: "2026-09-03",
    startTime: "09:00",
    endTime: "09:30",
    available: true,
    recurring: false,
  },
  {
    id: "slot-002",
    doctorId: DEMO_DOCTOR.id,
    date: "2026-09-03",
    startTime: "10:00",
    endTime: "10:30",
    available: false,
    recurring: false,
  },
  {
    id: "slot-003",
    doctorId: DEMO_DOCTOR.id,
    date: "2026-09-03",
    startTime: "11:00",
    endTime: "12:00",
    available: true,
    recurring: false,
  },
  {
    id: "slot-004",
    doctorId: DEMO_DOCTOR.id,
    date: "2026-09-04",
    startTime: "09:00",
    endTime: "09:30",
    available: false,
    recurring: false,
  },
  {
    id: "slot-005",
    doctorId: DEMO_DOCTOR.id,
    date: "2026-09-04",
    startTime: "10:00",
    endTime: "11:00",
    available: true,
    recurring: false,
  },
  {
    id: "slot-006",
    doctorId: DEMO_DOCTOR.id,
    date: "2026-09-05",
    startTime: "10:00",
    endTime: "10:30",
    available: false,
    recurring: false,
  },
  {
    id: "slot-007",
    doctorId: DEMO_DOCTOR.id,
    date: "2026-09-05",
    startTime: "14:00",
    endTime: "16:00",
    available: true,
    recurring: false,
  },
  {
    id: "slot-008",
    doctorId: DEMO_DOCTOR.id,
    date: "2026-09-06",
    startTime: "09:30",
    endTime: "12:30",
    available: true,
    recurring: true,
    recurrence: "weekly",
  },
  {
    id: "slot-009",
    doctorId: DEMO_DOCTOR.id,
    date: "2026-09-08",
    startTime: "13:00",
    endTime: "15:00",
    available: true,
    recurring: false,
  },
  {
    id: "slot-010",
    doctorId: DEMO_DOCTOR.id,
    date: "2026-09-10",
    startTime: "09:00",
    endTime: "12:00",
    available: true,
    recurring: true,
    recurrence: "weekly",
  },

  // Dr. Martin Cole — dermatology slots
  {
    id: "slot-101",
    doctorId: DEMO_DOCTOR_2.id,
    date: "2026-09-04",
    startTime: "15:00",
    endTime: "15:30",
    available: false,
    recurring: false,
  },
  {
    id: "slot-102",
    doctorId: DEMO_DOCTOR_2.id,
    date: "2026-09-04",
    startTime: "16:00",
    endTime: "17:30",
    available: true,
    recurring: false,
  },
  {
    id: "slot-103",
    doctorId: DEMO_DOCTOR_2.id,
    date: "2026-09-05",
    startTime: "11:00",
    endTime: "13:00",
    available: true,
    recurring: false,
  },
  {
    id: "slot-104",
    doctorId: DEMO_DOCTOR_2.id,
    date: "2026-09-10",
    startTime: "10:00",
    endTime: "12:00",
    available: true,
    recurring: true,
    recurrence: "weekly",
  },
];
