import type { Doctor } from "@/types/doctor";

export const doctors: Doctor[] = [
  {
    id: "doc-001",
    name: "Dr. Anika Rao",
    email: "anika.rao@example.com",
    phone: "9876543210",
    specialty: "General Medicine",
    qualification: "MBBS, MD",
    experienceYears: 10,
    registrationNumber: "MED12345",
    address: "Bangalore",
    consultationFee: 800,
    available: true,
  },
  {
    id: "doc-002",
    name: "Dr. Martin Cole",
    email: "martin.cole@example.com",
    phone: "9876543211",
    specialty: "Dermatology",
    qualification: "MBBS, MD Dermatology",
    experienceYears: 8,
    registrationNumber: "MED12346",
    address: "Bangalore",
    consultationFee: 1000,
    available: true,
  },
  {
    id: "doc-003",
    name: "Dr. Sarah Wilson",
    email: "sarah.wilson@example.com",
    phone: "9876543212",
    specialty: "Cardiology",
    qualification: "MBBS, MD Cardiology",
    experienceYears: 12,
    registrationNumber: "MED12347",
    address: "Bangalore",
    consultationFee: 1200,
    available: false,
  },
];